# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaorder',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
